{{- $pathfile := printf "envs/%s/.secret.third-eye" .Values.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-third-eye-secret"
stringData:
  {{ range .Files.Lines $pathfile }}
  {{   if . }}
  {{     $parts := regexSplit "=" . 2 }}
  {{     index $parts 0  }}: {{ index $parts 1 }}
  {{   end }}
  {{ end }}